### DISCUSSION TITLE
how can i set this up in docker

### DISCUSSION THREAD

**Discussion by aniel300** [jkwill87/mnamer#167] [Questions] [answered]
i tried following the wiki but my knowledge is limited and i was not able to set it up, please help

**Comment by jkwill87** [comment]
What did you try and what specifically are you having issues with?

**Reply by aniel300** [reply]
the directions for docker are not clear or maybe is me, attached is a screenshot of what i have so far in my docker compose file 
![Code_9Aw1ZNmsSl](https://user-images.githubusercontent.com/7571729/138540562-f1815507-3316-44fc-b45f-04dccef92b7f.png)

**Comment by jkwill87** [comment, marked as answer]
> the directions for docker are not clear

Yea, I'm not looking to explain how to use docker or docker-compose. There are any number of use cases that I can't anticipate and there are better resources available than I care to rewrite here. Either way, hopefully this can help get you on the right path. Best of luck!

# Observations:
- Your `command` doesn't seem at all related to mnamer, I assume that's for some other service in your docker-compose file.
- I notice that you're using `restart: unless-stopped`. Just want to make sure that you know that this service isn't a deamon, its run once then exists.
- It's not clear why you are passing all these options as environment variables.


# Suggestions:
- Either use a config file and pass that as a volume mount or override `command` which is what gets passed to mnamer.
- Use docker-compose run to test out your settings, e.g. `docker-compose run --rm mnamer <arguments...>`.

# Examples:

Not tested.

```yml
# using a config file
mnamer:
    image: jkwill87/mnamer
    volumes:
        - /media/movies:/mnt/movies
        - /media/episodes:/mnt/episodes
        - mnamer-config.json:/mnt/.mnamer-v2.json

# overriding command
mnamer:
    image: jkwill87/mnamer
    volumes:
        - /media/movies:/mnt/movies
        - /media/episodes:/mnt/episodes
    command: --batch --episode-directory=/mnt/episodes --movie-directory=/mnt/movies --movie-format='{name} ({year}){extension}'
```

**Comment by aniel300** [comment]
thank u, i will give it a try

**Comment by gingerbeardman** [comment]
Correction to the command argument (`--movie-directory` should be singular):
`--movie-directory=/mnt/movies`

**Comment by gingerbeardman** [comment]
I'm running with a Task Scheduler script as follows:

```bash
cd /volume1/video/Scripts
docker-compose run --rm mnamer -b -r /mnt/new --episode-directory=/mnt/episodes --movie-directory=/mnt/movies
```

in `/volume1/video/Scripts` I have `docker-compose.yml`:
```yml
mnamer:
    image: jkwill87/mnamer
    volumes:
        - /volume1/video/Movies:/mnt/movies
        - /volume1/video/TV:/mnt/episodes
        - /volume1/video/_New:/mnt/new
```

I guess I could combine into one config `docker-compose.yml` but to be honest I stopped as soon as I got it working. This setup was exhausting.

This prevents errors that the "Docker container stopped unexpectedly" in the DSM notifications.
